# Week 1

In [1]:
sales_record = {
    'price': 3.24,
    'num_items': 4,
    'person': 'Chris'}

sales_statement = '{} bought {} item(s) at a price of {} each for a total of {}'

print(sales_statement.format(sales_record['person'],
                             sales_record['num_items'],
                             sales_record['price'],
                             sales_record['num_items']*sales_record['price']))

In [2]:
import csv
% precision 2
with open('./Data/mpg.csv') as csvfile:
    mpg=list(csv.DictReader(csvfile))
#把每一行的数据都座位一个dictionary的形式出现
mpg[:1]
# 看这个list有多少个东西，就是element 的话就用 len()
#len(mpg)

[OrderedDict([('', '1'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'auto(l5)'),
              ('drv', 'f'),
              ('cty', '18'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')])]

In [3]:
mpg[0].keys()    #一个list里面的key 其实就是column name

odict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])

In [4]:
mpg[0]['cty']

'18'

In [5]:
i = 0
sumcty =0
for i in mpg:
    sumcty += float(i['cty'])  #############???????????????????

sumcty/len(mpg)

16.86

In [6]:
sum(float(d['cty']) for d in mpg)/len(mpg)

16.86

In [7]:
cylinders = set(d['cyl'] for d in mpg)
cylinders

{'4', '5', '6', '8'}

In [8]:
# inorder to calculate cty per cylinders 
ctympgbycyl = []

for c in cylinders:
    summpg =0
    cyltypecount = 0
    for d in mpg:
        if d['cyl'] ==c:
            summpg +=float(d['cty'])
            cyltypecount +=1
    ctympgbycyl.append((c, summpg/cyltypecount))

ctympgbycyl.sort(key=lambda x: x[0])
ctympgbycyl

[('4', 21.01), ('5', 20.50), ('6', 16.22), ('8', 12.57)]

In [9]:
# find the aerage highway mpg for vehicle classes
vehicleclasses =set(d['class'] for d in mpg)
vehicleclasses

{'2seater', 'compact', 'midsize', 'minivan', 'pickup', 'subcompact', 'suv'}

In [10]:
highwaympgbyclass =[]

for c in vehicleclasses:
    summpg =0
    classtypecount =0
    for d in mpg:
        if d['class']==c:
            summpg +=float(d['hwy'])
            classtypecount +=1
    highwaympgbyclass.append((c, summpg/classtypecount))

highwaympgbyclass
    

[('pickup', 16.88),
 ('compact', 28.30),
 ('midsize', 27.29),
 ('suv', 18.13),
 ('2seater', 24.80),
 ('minivan', 22.36),
 ('subcompact', 28.14)]

# Dates and Times 

In [11]:
import datetime as dt
import time as tm

In [12]:
tm.time()

1523505243.42

In [13]:
dtnow =dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2018, 4, 11, 20, 54, 3, 442276)

In [14]:
dtnow.year,dtnow.month,dtnow.day,dtnow.hour,dtnow.minute,dtnow.second

(2018, 4, 11, 20, 54, 3)

In [15]:
delta = dt.timedelta(days =100)
delta

datetime.timedelta(100)

In [16]:
today=dt.date.today()

In [17]:
today-delta

datetime.date(2018, 1, 1)

## Advanced Python Objects, map()

In [18]:
# you don't declare variables within the object, just start using them   must include self
class Person:
    department = 'School of Information'
    
    def set_name(self, new_name):
        self.name = new_name
    def set_location(self,new_location):
        self.location = new_location

In [19]:
person =Person()
person.set_name('Christopher Brooks')
person.set_location('Ann Arbor, MI, USA')
print('{} live in {} and works in the department {}'.format(person.name, person.location, person.department))

Christopher Brooks live in Ann Arbor, MI, USA and works in the department School of Information


### MAP()

In [20]:
# map(function, iterable,...) return an iterator that applies function to every item of iterable, yielding the results. If 
# additional iterable arguments are passed, function must take that many arguments and is applied to the items from all iterables 
# in parallel.With multiple iterrables , ther iterator stops when the shorterst iterable is exhausted. For cases where the function
# inputs are already arranged into argument tuples, see itertools.starmap()

In [21]:
# you want to choose the minimun b/t two stores
store1 = [10.00,11.00,12.34,2.34]
store2 = [9.00,11.10,12.34,2.01]
cheapest =map(min,store1,store2)
cheapest    ## result is a lazy evaluation

In [22]:
for item in cheapest:
    print(item)

9.0
11.0
12.34
2.01


In [23]:
# get people's title and last name : output like: Dr.Brooks using map
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    title =person.split()[0]
    lastname=person.split()[-1]
    return ' {}{}'.format(title,lastname)     #####???? 这里为什么是{ }    跟dictionary 有关系吗？

list(map(split_title_and_name,people))

[' Dr.Brooks', ' Dr.Collins-Thompson', ' Dr.Vydiswaran', ' Dr.Romero']

### Lambada and List Comphehensions

In [24]:
my_function = lambda a,b,c: a+b    ##simple expression

In [25]:
my_function(1,2,3)

3

In [26]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split()[-1]

#option 1
#for person in people:
    #print(split_title_and_name(person) == (lambda person:person.split()[0]+' '+person.split()[-1] ))
    #print(split_title_and_name(person) == (lambda x:x.split()[0] + ' '+x.split()[-1])(person))

#option 2
list(map(split_title_and_name, people)) == list(map(lambda person: person.split()[0]+' '+person.split()[-1],people))

True

In [27]:
my_list = []
for number in range(0,10):
    if number % 2 ==0:
        my_list.append(number)
my_list

[0, 2, 4, 6, 8]

In [28]:
#rewrite the above function using list comphehensions
my_list2 = [number for number in range(0,10) if number % 2 ==0]
my_list2

[0, 2, 4, 6, 8]

In [29]:
def times_tables():
    lst = []
    for i in range(10):
        for j in range (10):
            lst.append(i*j)
    return lst

times_tables() == [i*j for i in range(10) for j in range(0,10)]

True

In [30]:
## Question  userid should be two letters followed by two numbers (eg: aa49)
lowercase = 'abcdefghijklmnopqrstuvwxyz'
digits = '0123456789'
correct_answer = [a+b+c+d for a in lowercase for b in lowercase for c in digits for d in digits]


### NumPy

In [31]:
import numpy as np

#### Creating Arrays

In [32]:
mylist=[1,2,3]
x =np.array(mylist)
x

array([1, 2, 3])

In [33]:
y = np.array([4,5,6])
y

array([4, 5, 6])

In [34]:
m = np.array([[7,8,9],[10,11,12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [35]:
m.shape

(2, 3)

In [36]:
n = np.arange(0,30,2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [37]:
n =n.reshape(3,5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [38]:
o =np.linspace(0,4,9)
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [39]:
o.reshape(3,3)

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [40]:
o.resize(3,3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [41]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [42]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [45]:
np.array([1,2,3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [46]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [47]:
p =np.ones([2,3],int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [48]:
np.vstack([p,2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [49]:
np.hstack([p,2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

#### Operations 

In [50]:
x+y

array([5, 7, 9])

In [51]:
x * y

array([ 4, 10, 18])

In [52]:
x.dot(y)

32

In [53]:
z =np.array([y,y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [54]:
z.shape

(2, 3)

In [55]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [56]:
z.T.shape

(3, 2)

In [57]:
z.dtype

dtype('int32')

In [58]:
z = z.astype('f')

In [59]:
z.dtype

dtype('float32')

In [60]:
a = np.array([-4,-2,1,3,5])

In [61]:
a.sum()

3

In [62]:
a.max()

5

In [63]:
a.mean()

0.60

In [64]:
a.std()

3.26

In [65]:
a.argmax()

4

# Indexing / Slicing

In [66]:
a = np.arange(13)**2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

In [67]:
a[0],a[4],a[0:3]

(0, 16, array([0, 1, 4], dtype=int32))

In [68]:
a[1:5]

array([ 1,  4,  9, 16], dtype=int32)

In [69]:
a[-4:]

array([ 81, 100, 121, 144], dtype=int32)

In [70]:
a[-5::2]

array([ 64, 100, 144], dtype=int32)

In [71]:
r=np.arange(36)

In [72]:
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [73]:
r.resize(6,6)

In [74]:
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [75]:
r[2,2]

14

In [76]:
r[3, 3:6]

array([21, 22, 23])

In [77]:
r[:2,:-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [78]:
r[-1,::2]

array([30, 32, 34])

In [79]:
r[r>30]=30

In [80]:
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [81]:
r2 =r[:3,:3]

In [82]:
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [83]:
r2[:]=0

In [84]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

## Be careful when working with numpy arrays, subset changed, the originial data will change as well

In [85]:
r_copy=r.copy()

In [86]:
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [87]:
r_copy[:]=10

In [88]:
print(r_copy)
print()
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


# Iterating over arrays

In [89]:
test =np.random.randint(0,10,(4,3))

In [90]:
test

array([[2, 9, 8],
       [2, 2, 2],
       [0, 0, 4],
       [7, 9, 6]])

In [91]:
for row in test:
    print(row)

[2 9 8]
[2 2 2]
[0 0 4]
[7 9 6]


In [92]:
for i in range(len(test)):
    print(test[i])

[2 9 8]
[2 2 2]
[0 0 4]
[7 9 6]


In [93]:
for i, row in enumerate(test):
    print('row',i,'is',row)

row 0 is [2 9 8]
row 1 is [2 2 2]
row 2 is [0 0 4]
row 3 is [7 9 6]


In [94]:
test2=test**2

In [95]:
test2

array([[ 4, 81, 64],
       [ 4,  4,  4],
       [ 0,  0, 16],
       [49, 81, 36]], dtype=int32)

In [96]:
for i,j in zip(test,test2):  ## using zip to iterate both arrarys 
    print(i,"+",j,'=',i+j)

[2 9 8] + [ 4 81 64] = [ 6 90 72]
[2 2 2] + [4 4 4] = [6 6 6]
[0 0 4] + [ 0  0 16] = [ 0  0 20]
[7 9 6] + [49 81 36] = [56 90 42]
